echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "This is modified Intune portal which is synced to the ServiceNow0"
echo "INC985089 is resolved by the Vishwajeet"
